#!/bin/sh -f

mvn install:install-file -Dfile=/Users/colesmith/coatjava/lib/services/clas12detector-ec-1.0-SNAPSHOT.jar   -DgroupId=org.jlab.services -DartifactId=clas12detector-ec   -Dpackaging=jar -Dversion=1.0-SNAPSHOT
mvn install:install-file -Dfile=/Users/colesmith/coatjava/lib/services/clas12detector-tof-1.0-SNAPSHOT.jar  -DgroupId=org.jlab.services -DartifactId=clas12detector-tof  -Dpackaging=jar -Dversion=1.0-SNAPSHOT
mvn install:install-file -Dfile=/Users/colesmith/coatjava/lib/services/clas12detector-eb-1.0-SNAPSHOT.jar   -DgroupId=org.jlab.services -DartifactId=clas12detector-eb   -Dpackaging=jar -Dversion=1.0-SNAPSHOT
mvn install:install-file -Dfile=/Users/colesmith/coatjava/lib/clas/coat-libs-6.6.5-SNAPSHOT.jar             -DgroupId=org.jlab.coat     -DartifactId=coat-libs           -Dpackaging=jar -Dversion=6.6.5-SNAPSHOT
mvn install:install-file -Dfile=./external-dependencies/clas12ana-3.0.jar                                   -DgroupId=org.jlab.fc       -DartifactId=clas12ana           -Dpackaging=jar -Dversion=3.0
mvn install:install-file -Dfile=./external-dependencies/3DViewer-1.0-SNAPSHOT.jar                           -DgroupId=org.jlab.fc       -DartifactId=3DViewer            -Dpackaging=jar -Dversion=1.0-SNAPSHOT
mvn install:install-file -Dfile=./external-dependencies/ca-1.0.0.jar                                        -DgroupId=org.jlab.fc       -DartifactId=ca                  -Dpackaging=jar -Dversion=1.0.0
mvn install:install-file -Dfile=./external-dependencies/disruptor-3.3.0.jar                                 -DgroupId=org.jlab.fc       -DartifactId=disruptor           -Dpackaging=jar -Dversion=3.3.0
mvn install:install-file -Dfile=./external-dependencies/geometry-viewer-2.0-SNAPSHOT.jar                    -DgroupId=org.jlab.fc       -DartifactId=geometry-viewer     -Dpackaging=jar -Dversion=2.0-SNAPSHOT
mvn install:install-file -Dfile=./external-dependencies/jlog-2.9.0.jar                                      -DgroupId=org.jlab.elog     -DartifactId=elog                -Dpackaging=jar -Dversion=2.9.0
mvn install:install-file -Dfile=./external-dependencies/javaGeom-0.11.2.jar                                 -DgroupId=org.jlab.fc       -DartifactId=javaGeom            -Dpackaging=jar -Dversion=0.11.2
mvn install:install-file -Dfile=./external-dependencies/jroot-6.06.00.jar                                   -DgroupId=org.jlab.fc       -DartifactId=jroot               -Dpackaging=jar -Dversion=6.06.00


 
